Regsvr32 /s /u GradientCommand.ocx
Regsvr32 /s /u ubGrid.ocx
Regsvr32 /s /u Frame-Xp.ocx
Regsvr32 /s /u HookMenu.ocx
Regsvr32 /s /u RICHTX32.OCX
Regsvr32 /s /u mscomctl.ocx
Regsvr32 /s /u MSCHRT20.OCX
Regsvr32 /s /u NotifyIcon.ocx
Regsvr32 /s /u TABCTL32.OCX
Regsvr32 /s /u MSCOMCT2.OCX
Regsvr32 /s /u progressbar-xp.ocx